//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryDetail
    {
        public int Id { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public int Priority { get; set; }
        public int ParenId { get; set; }
        public string Metakey { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public Nullable<bool> IsNewLabel { get; set; }
        public bool IsHasBanner { get; set; }
        public string BannerImage { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
