//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentPageSlug
    {
        public int Id { get; set; }
        public string PageSlug { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public int ComponentTypeId { get; set; }
        public Nullable<int> QuantityRecord { get; set; }
        public int Priority { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> Updated_by { get; set; }
    
        public virtual ComponentType ComponentType { get; set; }
    }
}
