//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentSubDescription
    {
        public int Id { get; set; }
        public int ComponentId { get; set; }
        public string PageSlug { get; set; }
        public string SubTitle { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ReferenceLink { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> Updated_by { get; set; }
    }
}
