//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<CategoryDetail> CategoryDetails { get; set; }
        public virtual DbSet<Category> Categorys { get; set; }
        public virtual DbSet<ComponentItem> ComponentItems { get; set; }
        public virtual DbSet<ComponentPageSlug> ComponentPageSlugs { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ComponentSubDescription> ComponentSubDescriptions { get; set; }
        public virtual DbSet<ComponentType> ComponentTypes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<PageCategory> PageCategories { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PageSlug> PageSlugs { get; set; }
        public virtual DbSet<ProductCategoryDetail> ProductCategoryDetails { get; set; }
        public virtual DbSet<ProductCategory> ProductCategorys { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<TopicDetail> TopicDetails { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    }
}
