//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectImages = new HashSet<ProjectImage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProjectCategoryId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Customer { get; set; }
        public int Size { get; set; }
        public Nullable<System.DateTime> TimeProject { get; set; }
        public string JobDescription { get; set; }
        public string Slug { get; set; }
        public string ThumbnailImage { get; set; }
        public string Content { get; set; }
        public int Priority { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public string Address { get; set; }
    
        public virtual ProjectCategory ProjectCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImage> ProjectImages { get; set; }
    }
}
